# Generated by Django 3.0.8 on 2020-11-29 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
