# Generated by Django 3.0.8 on 2020-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='amazon'),
        ),
        migrations.AddField(
            model_name='book',
            name='evaluation',
            field=models.IntegerField(default=10, verbose_name='評価'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rakuten',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rakuten'),
        ),
    ]
