# Generated by Django 3.0.8 on 2020-12-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('profile', models.TextField(verbose_name='プロフィール')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
            ],
        ),
    ]
